name: main-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'CreatiCoding/creco.today'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Update Version
        run: |
          echo "{ \"version\": \"$(git rev-parse HEAD)\" }" > dist/web-version.json

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 sync dist s3://www.creco.today --acl public-read
          aws cloudfront create-invalidation --distribution-id E2N0PM6HB8VW5S --paths "/*"
          aws cloudfront create-invalidation --distribution-id E3NFEMJV5K7IF1 --paths "/*"
          - name: action-slack

      - name: alert to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
